version: '2'
services:
  sampleapplication-app:
    image: sampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://sampleapplication-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=SampleApplication
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8989:8989
  sampleapplication-mongodb:
    extends:
      file: mongodb.yml
      service: sampleapplication-mongodb
